dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1'

dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}

# optional for verifying the contract source code
networks:
  development:
    verify : false
  kovan:
    verify : false
  rinkeby:
    verify: false